server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gongibap
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true
  thymeleaf:
    enabled: true
    dialects: nz.net.ultraq.thymeleaf.LayoutDialect
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML
    encoding: UTF-8
  servlet:
    content-type: text/html;charset=UTF-8
  view-names: error
  check-template-location: true
  template-resolver-order: 0




